### ISSUE TITLE
custom dataset image resolutions

### ISSUE THREAD

**Issue by lhammond** [datitran/raccoon_dataset#11]
Hi Dat,
I was able to get some detection working with a custom dataset and am now trying to start from the model checkpoint of a previous run while adding a new class.  

Here's what I've done
1. I uploaded my model.ckpt-PREFIX into a gs:// bucket and updated ssd-config to point to that checkpoint by using the fine_tune_checkpoint config param
2. For each of my two classes I created the csvs, then ran the notebook so split them into test/train..then consolidated them into a single test and train.csv
3. put all of the images for both classes into the images directory and made sure that the image path in generate_tfrecord.py was pointing to the correct directory
4. ran the script to create my tfrecords
5. launched the training and eval jobs ..see loss and perfomance screenshots below
6. stopped the training / eval jobs and downloaded the most recent checkpoint
7. used object_detection/export_inference_graph.py to output the graph
8. uploaded frozen_inference_graph.pb to my raspi
9. updated my label_maps.pbtxt to include my 2 classes

![image](https://user-images.githubusercontent.com/229602/29795173-1b6d370c-8c19-11e7-9a59-11e92d40c37c.png)

![image](https://user-images.githubusercontent.com/229602/29795348-d7308818-8c19-11e7-9dfa-ccfbb1ac8204.png)

I am not seeing very good performance and my second class is never accurately detected, even when increasing the threshold to 0.1

A couple of questions
- all of my images are taken with the same camera, and identical sizes because I used ImageMagick mogrify to resize them to 640x480...should I be randomizing the sizes/resolutions?
- is my general approach ok?

thanks!
@lhammond

**Comment by datitran** [comment]
Well your approach is fine. I can't really tell about your results just that mAP and Total loss looks fine to me. How does your evaluation of the image evolve? Usually when your mAP increase to 0.6 for the second class, you should at least see something. Concerning the image stuff, this should be fine. It's rather more important to have objects with different angles, rotation etc...
