### ISSUE TITLE
split labels

### ISSUE THREAD

**Issue by liuxinyuk** [datitran/raccoon_dataset#18]
# take first 200 files
train = pd.concat([grouped_list[i] for i in train_index])
test = pd.concat([grouped_list[i] for i in test_index])
len(train), len(test)

out :(173, 44)

train_index=160 ,test_index=40. why there is 173 and 44 ?

**Comment by datitran** [comment]
Because some images have more than one Raccoons...

**Comment by liuxinyuk** [comment]
@datitran thank you !
