### ISSUE TITLE
can't use generate tfrecords 

### ISSUE THREAD

**Issue by allenlaitw** [datitran/raccoon_dataset#20]
hello, i want to use my own data to retrain , so i add some classes at class_text_to_int(row_label)
but i got some error , would you help me to take a look?

mspic@mspic-SYS-7048GR-TR:~/Downloads/models$ python our_tfrecord.py --csv_input=data/train_labels.csv  --output_path=train.record
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "our_tfrecord.py", line 117, in <module>
    tf.app.run()
  File "/home/mspic/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "our_tfrecord.py", line 108, in main
    tf_example = create_tf_example(group, path)
  File "our_tfrecord.py", line 82, in create_tf_example
    classes_text.append(row['class'].encode('utf8'))
AttributeError: 'int' object has no attribute 'encode'

**Comment by datitran** [comment]
The error says that the class is an `integer` and therefore you cannot use encode. So cast the class as `str` and then it should work.

**Comment by allenlaitw** [comment]
I have cast the class as  str at the line30 and line65 but i got the same problem above.

**Comment by datitran** [comment]
@allenlaitw Can you check if this is really a `str` object? For example, you could print out the type of the variable.

**Comment by allenlaitw** [comment]
Thanks Dat, i fix the error by changing the class to str ,very appreciate your helping.

**Comment by Mackillst** [comment]
Hi guys,

I got these errors 

raceback (most recent call last):
  File "generate_tfrecord.py", line 119, in <module>
    tf.app.run()
  File "C:\Users\Abood\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "generate_tfrecord.py", line 110, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 85, in create_tf_example
    classes.append(class_text_to_int(row['class'].encode('utf8')))
AttributeError: 'bytes' object has no attribute 'encode'

**Comment by cindysillence** [comment]
what is my class is just nummer. I made the csv file coloum for the class type of text. But it stiil not work....

**Comment by BharathKR** [comment]
find this code:
classes_text.append(row['class'].encode('utf8'))
classes.append(class_text_to_int(row['class']))

and change it to

classes_text.append(str(row['class']).encode('utf8'))
classes.append(class_text_to_int(str(row['class'])))
