### ISSUE TITLE
How to create label map?

### ISSUE THREAD

**Issue by swetshaw** [datitran/raccoon_dataset#21]
'''
# TO-DO replace this with label map
def class_text_to_int(row_label):
    if row_label == 'raccoon':
        return 1
    else:
        None 
'''

I am training on a single class named "mobile". How to create label map? what to replace the above code with?

**Comment by datitran** [comment]
Well if you train on a single class, you can do something like this:

"""
def class_text_to_int(row_label):
    if row_label == 'mobile':
        return 1
    else:
        None
"""

For more than one class:

"""
def class_text_to_int(row_label):
    if row_label == 'mobile':
        return 1
    if row_label == 'nonmobile':
        return 2
    else:
        None
"""

And for more than two class, you should get the idea...

**Comment by munnam77** [comment]
For more than one class:

def class_text_to_int(row_label):
    if row_label == 'mobile':
        return 1
    if row_label == 'nonmobile':
        return 2
    else:
        return 0
