### ISSUE TITLE
issue with tensorboard

### ISSUE THREAD

**Issue by seahawks8** [datitran/raccoon_dataset#24]
wondering if this is an issue or not, I am missing the issue tab "cross post from stackoverflow"
[https://stackoverflow.com/questions/46506946/is-it-necessary-to-copy-images-and-annotations-to-cloud-bucket-when-training-obj](url)

and I am missing "Mean Precision graph" from my tensorboard, perhaps I missed a step?

thanks

**Comment by datitran** [comment]
The link is broken...

**Comment by seahawks8** [comment]
My apologies
https://stackoverflow.com/questions/46506946/is-it-necessary-to-copy-images-and-annotations-to-cloud-bucket-when-training-obj

**Comment by seahawks8** [comment]
Basically I am missing the images tab in tensorboard and I don’t know where to find the precision graph?

**Comment by datitran** [comment]
The question on Stackoverflow is kind of different than the one on git.. I answered one part on Stack for the other part. I have no idea why you don't have no images tab. Usually when you run the evaluation job, it will show up. The precision graph is created by the training script and you can find it in the scalars tab. It would also make sense to remove the tags matching.

**Comment by seahawks8** [comment]
Yea I know, do you load the images to the bucket as well?

**Comment by datitran** [comment]
No I don't! See my answer on Stackoverflow.

**Comment by seahawks8** [comment]
yea, I am not sure why the precision/map does not show up on my tensorboard, but will sort it out.
