### ISSUE TITLE
ValueError: axis = 0 not in [0, 0)

### ISSUE THREAD

**Issue by ngksai93** [datitran/raccoon_dataset#45]
python /home/gopalakrishna/work/models-0375c800c767db2ef070cee1529d8a50f42d1042/object_detection/train.py --logtostderr=/home/gopalakrishna/log_dir --pipeline_config_path=/home/gopalakrishna/PathToConfig/ssd_mobilenet_v1_coco.config --train_dir=/home/gopalakrishna/model
/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/gopalakrishna/work/models-0375c800c767db2ef070cee1529d8a50f42d1042/object_detection/train.py", line 198, in <module>
    tf.app.run()
  File "/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/gopalakrishna/work/models-0375c800c767db2ef070cee1529d8a50f42d1042/object_detection/train.py", line 194, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/gopalakrishna/work/models-0375c800c767db2ef070cee1529d8a50f42d1042/object_detection/trainer.py", line 192, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "/home/gopalakrishna/work/models-0375c800c767db2ef070cee1529d8a50f42d1042/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "/home/gopalakrishna/work/models-0375c800c767db2ef070cee1529d8a50f42d1042/object_detection/trainer.py", line 133, in _create_losses
    losses_dict = detection_model.loss(prediction_dict)
  File "/home/gopalakrishna/work/models-0375c800c767db2ef070cee1529d8a50f42d1042/object_detection/meta_architectures/ssd_meta_arch.py", line 431, in loss
    location_losses, cls_losses, prediction_dict, match_list)
  File "/home/gopalakrishna/work/models-0375c800c767db2ef070cee1529d8a50f42d1042/object_detection/meta_architectures/ssd_meta_arch.py", line 565, in _apply_hard_mining
    match_list=match_list)
  File "/home/gopalakrishna/work/models-0375c800c767db2ef070cee1529d8a50f42d1042/object_detection/core/losses.py", line 445, in __call__
    location_losses = tf.unstack(location_losses)
  File "/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 989, in unstack
    (axis, -value_shape.ndims, value_shape.ndims))
ValueError: axis = 0 not in [0, 0)

**Comment by ngksai93** [comment]
please help me anybody

**Comment by thriskel** [comment]
check the pipeline.config file it has these lines:
```
fine_tune_checkpoint: "PATH_TO_CKPT/model.ckpt"
from_detection_checkpoint: false
```
change the second line to "true" instead of "false":
`from_detection_checkpoint: true`

**Comment by ngksai93** [comment]
ya i did like that only 
see this is my pipeline.config file 

# SSD with Mobilenet v1 configuration for MSCOCO Dataset.
# Users should configure the fine_tune_checkpoint field in the train config as
# well as the label_map_path and input_path fields in the train_input_reader and
# eval_input_reader. Search for "PATH_TO_BE_CONFIGURED" to find the fields that
# should be configured.

model {
  ssd {
    num_classes: 1
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    anchor_generator {
      ssd_anchor_generator {
        num_layers: 6
        min_scale: 0.2
        max_scale: 0.95
        aspect_ratios: 1.0
        aspect_ratios: 2.0
        aspect_ratios: 0.5
        aspect_ratios: 3.0
        aspect_ratios: 0.3333
      }
    }
    image_resizer {
      fixed_shape_resizer {
        height: 300
        width: 300
      }
    }
    box_predictor {
      convolutional_box_predictor {
        min_depth: 0
        max_depth: 0
        num_layers_before_predictor: 0
        use_dropout: false
        dropout_keep_probability: 0.8
        kernel_size: 1
        box_code_size: 4
        apply_sigmoid_to_scores: false
        conv_hyperparams {
          activation: RELU_6,
          regularizer {
            l2_regularizer {
              weight: 0.00004
            }
          }
          initializer {
            truncated_normal_initializer {
              stddev: 0.03
              mean: 0.0
            }
          }
          batch_norm {
            train: true,
            scale: true,
            center: true,
            decay: 0.9997,
            epsilon: 0.001,
          }
        }
      }
    }
    feature_extractor {
      type: 'ssd_mobilenet_v1'
      min_depth: 16
      depth_multiplier: 1.0
      conv_hyperparams {
        activation: RELU_6,
        regularizer {
          l2_regularizer {
            weight: 0.00004
          }
        }
        initializer {
          truncated_normal_initializer {
            stddev: 0.03
            mean: 0.0
          }
        }
        batch_norm {
          train: true,
          scale: true,
          center: true,
          decay: 0.9997,
          epsilon: 0.001,
        }
      }
    }
    loss {
      classification_loss {
        weighted_sigmoid {
        }
      }
      localization_loss {
        weighted_smooth_l1 {
        }
      }
      hard_example_miner {
        num_hard_examples: 3000
        iou_threshold: 0.99
        loss_type: CLASSIFICATION
        max_negatives_per_positive: 3
        min_negatives_per_image: 0
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }
    normalize_loss_by_num_matches: true
    post_processing {
      batch_non_max_suppression {
        score_threshold: 1e-8
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SIGMOID
    }
  }
}

train_config: {
  batch_size: 24
  optimizer {
    rms_prop_optimizer: {
      learning_rate: {
        exponential_decay_learning_rate {
          initial_learning_rate: 0.004
          decay_steps: 800720
          decay_factor: 0.95
        }
      }
      momentum_optimizer_value: 0.9
      decay: 0.9
      epsilon: 1.0
    }
  }
  fine_tune_checkpoint:"/home/gopalakrishna/PathToConfig/model.ckpt.data-00000-of-00001"
  from_detection_checkpoint: true
  # Note: The below line limits the training process to 200K steps, which we
  # empirically found to be sufficient enough to train the pets dataset. This
  # effectively bypasses the learning rate schedule (the learning rate will
  # never decay). Remove the below line to train indefinitely.
  num_steps: 1000
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
  data_augmentation_options {
    ssd_random_crop {
    }
  }
}

train_input_reader: {
  tf_record_input_reader {
    input_path:"/home/gopalakrishna/PathToConfig/train.record"
  }
  label_map_path:"/home/gopalakrishna/PathToConfig/controlpanel_label_map.pbtxt"
}

eval_config: {
  num_examples: 10
  # Note: The below line limits the evaluation process to 10 evaluations.
  # Remove the below line to evaluate indefinitely.
  max_evals: 500
}

eval_input_reader: {
  tf_record_input_reader {
    input_path: "/home/gopalakrishna/PathToConfig/validation.record"
  }
  label_map_path: "/home/gopalakrishna/PathToConfig/controlpanel_label_map.pbtxt"
  shuffle: false
  num_readers: 1

}

**Comment by ngksai93** [comment]
Now i am getting the issue like below i think there is some issues in in tensorflow object detection api which i am using.p lease provide me the exact link what you used to train your model .

python /home/gopalakrishna/work/models-0375c800c767db2ef070cee1529d8a50f42d1042/object_detection/train.py --logtostderr=/home/gopalakrishna/log_dir --pipeline_config_path=/home/gopalakrishna/PathToConfig/ssd_mobilenet_v1_pets.config --train_dir=/home/gopalakrishna/model
/home/gopalakrishna/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From /home/gopalakrishna/approch2/models-master/research/object_detection/trainer.py:210: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
Traceback (most recent call last):
  File "/home/gopalakrishna/work/models-0375c800c767db2ef070cee1529d8a50f42d1042/object_detection/train.py", line 198, in <module>
    tf.app.run()
  File "/home/gopalakrishna/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/gopalakrishna/work/models-0375c800c767db2ef070cee1529d8a50f42d1042/object_detection/train.py", line 194, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/gopalakrishna/approch2/models-master/research/object_detection/trainer.py", line 228, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "/home/gopalakrishna/approch2/models-master/research/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "/home/gopalakrishna/approch2/models-master/research/object_detection/trainer.py", line 167, in _create_losses
    losses_dict = detection_model.loss(prediction_dict)
  File "/home/gopalakrishna/approch2/models-master/research/object_detection/meta_architectures/ssd_meta_arch.py", line 474, in loss
    location_losses, cls_losses, prediction_dict, match_list)
  File "/home/gopalakrishna/approch2/models-master/research/object_detection/meta_architectures/ssd_meta_arch.py", line 640, in _apply_hard_mining
    match_list=match_list)
  File "/home/gopalakrishna/approch2/models-master/research/object_detection/core/losses.py", line 515, in __call__
    location_losses = tf.unstack(location_losses)
  File "/home/gopalakrishna/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1074, in unstack
    (axis, -value_shape.ndims, value_shape.ndims))
ValueError: axis = 0 not in [0, 0)

**Comment by CBITT** [comment]
I'm having the same issue. @ngksai93 have you managed to sort it out?

**Comment by ngksai93** [comment]
you have any idea what it exactly CBITT

**Comment by HarshalGarg** [comment]
I have the same issue. Anyone solved it?

**Comment by HarshalGarg** [comment]
problem solved.
In your pipeline.config
make
    loss {
      classification_loss {
        weighted_sigmoid {
        }
      }
      localization_loss {
        weighted_smooth_l1 {
        }
      }
      hard_example_miner {
        num_hard_examples: 3000
        iou_threshold: 0.99
        loss_type: CLASSIFICATION
        max_negatives_per_positive: 3
        min_negatives_per_image: 0
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }


to 

    loss {
      classification_loss {
        weighted_sigmoid {
        anchorwise_output: true  #add this
        }
      }
      localization_loss {
        weighted_smooth_l1 {
        anchorwise_output: true  #add this
        }
      }
      hard_example_miner {
        num_hard_examples: 3000
        iou_threshold: 0.99
        loss_type: CLASSIFICATION
        max_negatives_per_positive: 3
        min_negatives_per_image: 0
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }

enjoy...

**Comment by jnvipul** [comment]
Correct. Also worked for me when I changed the config file. Damn! Wasted half a day :(

**Comment by ngksai93** [comment]
thank you harshal Garg

**Comment by ngksai93** [comment]
Finally i got solution for it . but i didn't change any code  like this in configuration file.

loss {
  classification_loss {
    weighted_sigmoid {
    anchorwise_output: true  #add this
    }
  }
  localization_loss {
    weighted_smooth_l1 {
    anchorwise_output: true  #add this
    }
  }
  hard_example_miner {
    num_hard_examples: 3000
    iou_threshold: 0.99
    loss_type: CLASSIFICATION
    max_negatives_per_positive: 3
    min_negatives_per_image: 0
  }
  classification_weight: 1.0
  localization_weight: 1.0
}

i thought the issue with the tfrecords.
this happens because when i labelled the images two images were labelled wrongly.
may be i thought this was the issue after that i again created the tfrecords  and finally i started  training.

**Comment by ngksai93** [comment]
thank you everyone for help

**Comment by josephsunnyajay** [comment]
Thanks a ton @HarshalGarg

**Comment by MounirB** [comment]
Thank you @HarshalGarg !

**Comment by jacobnzw** [comment]
You literally saved my ass @HarshalGarg !
