### ISSUE TITLE
What's the purpose of `output_inference_graph.pb`

### ISSUE THREAD

**Issue by JimReno** [datitran/raccoon_dataset#7]
Hi dat, thank's for your awesome raccoon-dataset!It looks great and  I try this by myself. Now the program is training.
I have a question that weather the  `output_inference_graph.pb` in `training` is useful. My directory structure for training is
+model
  -frozen_inference_graph.pb
  -graph.pbtxt
  -model.ckpt.data-00000-of-00001
  -model.ckpt.index
  -model.ckpt.meta
  -ssd_mobilenet_v1_pets.config
Would you please explain a bit about the `frozen_inference_graph.pb`. Is this graph just a pack which contains of millions of parameters of weights in it?

**Comment by datitran** [comment]
Hi @JimReno yes you're correct the frozen graph is just a single file where the meta graph and weights are cluttered together so that it can be used for inference. It's not really useful for training.
