### ISSUE TITLE
The output graph (raccoon-dataset/training/output_inference_graph.pb) can not detect anything

### ISSUE THREAD

**Issue by Abduoit** [datitran/raccoon_dataset#8]
Thanks for your amazing work, 

can u help me please, I used your data (images and annotaion) to train the model locally. I did `train.py` correctly. However, there is something wrong 

I updated my process in this [link](https://stackoverflow.com/questions/45802672/train-tensorflow-with-my-own-images-successfully-but-still-have-problems)

Thanks

**Comment by datitran** [comment]
Close as this question is already posted on stackoverflow.
